### ISSUE TITLE
[Enhancement] Prototyping the WorldRenderer Unity object that will tie all development together.

### ISSUE THREAD

**Issue by jamieyello** [MythologyScape/MythScape#2]
### Summary
This issue describes the development of the [WorldRenderer](https://github.com/MiniScaper/MythScape/blob/main/Assets/Scripts/WorldRenderer.cs), the Unity `MonoBehavior` that will enable us to edit the MMO map within Unity, as well as display the world for the player to see. It will encompass the entire world and most content within the game.

### Design Goal
WorldRenderer will be attached to an empty object. On user login, the renderer will populate itself with entities from the server. We will want these entities to be editable in the editor. When the developer chooses, they will click a sync button to update the server given they have a login token with appropriate permissions.

### Development Steps
 - [x] See if it's even possible for a script to edit an editor scene.
 - [x] Create a database structure for entities. This may be something as simple as storing JSON as a TEXT parameter.
 - [x] Create a DbAccess class for entities.
 - [x] Build out some REST API endpoints for editing entities. This endpoint should edit the loaded entities as well as entity data in the database.

### Final Steps
 - [ ] Create a final Unity scene that will render the world as we need it to.

### Future Issues
 - https://github.com/MiniScaper/MythScape/issues/3

**Comment by MccXaccess** [comment]
hey, Jamie!
we've moved all of our project files to https://github.com/MythologyScape/MythScape_RPG
feel free to commit your changed & updates to that repo:)

**Comment by jamieyello** [comment]
> hey, Jamie! we've moved all of our project files to [MythologyScape/MythScape_RPG](https://github.com/MythologyScape/MythScape_RPG) feel free to commit your changed & updates to that repo:)

I have a lot of work on this fork uncommitted. I'll commit to this fork, and then we can figure out merging that into the new one.

I'll transfer our old issues to the new one.

**Comment by jamieyello** [comment]
@MccXaccess What was the reason for a new fork of the project?

**Comment by jamieyello** [comment]
Closing this as Akseli is handling this now.
